import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'on-primary-container': '#c3e9f5',
        'on-tertiary-fixed-variant': '#613f26',
        'primary': '#002932',
        'inverse-on-surface': '#f1f1ef',
        'on-secondary-fixed-variant': '#584400',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#41484a',
        'on-primary-fixed-variant': '#284c56',
        'outline': '#71787b',
        'inverse-primary': '#a8ccd9',
        'on-secondary-container': '#776019',
        'on-secondary': '#ffffff',
        'on-surface': '#1a1c1b',
        'tertiary-fixed-dim': '#eebc9c',
        'on-tertiary-fixed': '#2e1502',
        'background': '#f9f9f7',
        'on-background': '#1a1c1b',
        'tertiary-container': '#53331b',
        'primary-fixed': '#c3e9f5',
        'outline-variant': '#c1c8ca',
        'surface-container-low': '#f4f4f2',
        'secondary-fixed': '#ffe08f',
        'on-secondary-fixed': '#241a00',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface': '#f9f9f7',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#e2c372',
        'tertiary-fixed': '#ffdcc5',
        'secondary-container': '#fddd89',
        'primary-fixed-dim': '#a8ccd9',
        'surface-container': '#eeeeec',
        'surface-container-high': '#e8e8e6',
        'inverse-surface': '#2f3130',
        'surface-bright': '#f9f9f7',
        'surface-variant': '#e2e3e1',
        'surface-dim': '#dadad8',
        'surface-container-highest': '#e2e3e1',
        'error': '#ba1a1a',
        'secondary': '#735c14',
      },
      fontFamily: {
        'label-sm': ['Manrope', 'sans-serif'],
        'headline-md': ['Newsreader', 'serif'],
        'headline-sm': ['Newsreader', 'serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'display-lg-mobile': ['Newsreader', 'serif'],
        'display-lg': ['Newsreader', 'serif'],
        'cursive': ['Allura', 'cursive'],
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      spacing: {
        'stack-md': '32px',
        'margin-desktop': '64px',
        'stack-sm': '16px',
        'stack-lg': '80px',
        'margin-mobile': '20px',
        'container-max': '1200px',
        'unit': '8px',
        'gutter': '24px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
export default config
